### ISSUE TITLE
update readme for new installation instructions via strap

### ISSUE THREAD

**Issue by AlJohri** [mikemcquaid/dotfiles#2]
hey there, just updating my dotfiles to work with strap and saw some outdated stuff in the readme

also what is `brew-cleanup-installed`?
https://github.com/MikeMcQuaid/dotfiles/blob/master/script/setup#L24

**Comment by MikeMcQuaid** [comment]
Fixed both of these, thanks. It was a script that cleaned up installed formulae that weren't in a whitelist and I've replaced it now with `brew bundle cleanup`.
