### ISSUE TITLE
rbenv folder overwritten?

### ISSUE THREAD

**Issue by AlJohri** [mikemcquaid/dotfiles#5]
Hi @MikeMcQuaid, it seems like the condition below:

```bash
    if [ -L "$HOMEFILE" ] && ! [ -d $DOTFILE ]
    then
      ln -sfv "$DIRFILE" "$HOMEFILE"
    else
      rm -rv "$HOMEFILE"
      ln -sv "$DIRFILE" "$HOMEFILE"
    fi
```

will attempt to `rm -rv` the `~/.rbenv` folder if the script is run a second time. 

Not sure if you were going for idempotency in this script, but apart from this, I've been able to run the `setup` script multiple times to update dependencies and symlinks.

Feel free to close if you don't care about idempotency for this project.

**Comment by AlJohri** [comment]
Not the best bash scripting, but I got around the issue like this for now:

```bash
echo $DOTFILE | egrep -q '(^rbenv/$|pyenv/$|nodenv/$)' && continue
```

```bash
mkdir -p $(pyenv root)
mkdir -p $(rbenv root)
mkdir -p $(nodenv root)

for FOLDER in rbenv pyenv nodenv; do
  if [ -d "$FOLDER" ]; then
    for DOTFILE in $FOLDER/*; do
      DIRFILE="$DOTFILESDIR/$DOTFILE"
      HOMEFILE="$HOME/.$DOTFILE"
      if [ -L "$HOMEFILE" ] && ! [ -d $DOTFILE ]
      then
        ln -sfv "$DIRFILE" "$HOMEFILE"
      elif ! [ -d $DOTFILE ]
      then
        rm -v "$HOMEFILE"
        ln -sv "$DIRFILE" "$HOMEFILE"
      else
        echo "ignoring $DOTFILE because it is a directory"
      fi
    done
  fi
done
```

**Comment by MikeMcQuaid** [comment]
> will attempt to rm -rv the ~/.rbenv folder if the script is run a second time.

Yep but as it's a symlink that's quick enough for us not to care. If it's a preexisting directory it'll kill it.

**Comment by AlJohri** [comment]
Ah, I see. Perhaps then you can add to the .gitignore:
```
rbenv/*
!rbenv/default-gems
```

I ran into the situation where I had the setup script run the first time but I didn't have the rbenv folder in my dotfiles. When I tried to later add the `rbenv` folder to my dotfiles, it attempted to delete the existing rbenv installation as it wasn't a symlink but an actual file.

Definitely a fringe case though.

**Comment by MikeMcQuaid** [comment]
There’s already `rbenv/*/` which implies your version; you can’t get Git to add an empty directory to a repository so unfortunately this is just going to be unfixable, sorry!
