### ISSUE TITLE
don't change PATH in sh.rc

### ISSUE THREAD

**Issue by AlJohri** [mikemcquaid/dotfiles#7]
hi, i've been working with some issues in pyenv and pipenv (python's new bundler) and I realized that the way my (and I believe your) shell is set up, is not entirely amenable to subshells / child processes

it seems as though putting changes to the PATH in `shrc` causes the subshell to rexecute the shrc thus re-adding things to the PATH. this issue is important when the parent process tries to run a subshell with a modified PATH, like a python virtualenv. unfortunately, the shrc ends up overriding those PATH changes via `add_to_path_start`. so my subshell's path will end up with `/usr/local/bin/:my_virtualenv_path:...` instead of `my_virtualenv_path` being at the beginning

seems like the better approach is to move any code that modifies the path like `add_to_path_start`, `rbenv init`, `pyenv init`, etc. into the profile. The profile should get run for `login` shells only and thus will not be rexecuted for subshells.

I'm making some changes in my own dotfiles to reflect this. just thought I'd drop you a note as well :) feel free to close

**Comment by MikeMcQuaid** [comment]
I've tried moving this to the profile (I think) in the past but I don't get the PATHs loading as I wanted  across macOS and Linux (as I think I actually want PATHs reset on subshells). Sorry!

**Comment by AlJohri** [comment]
Cool, I spent a while thinking about this issue so if you ever remember why you wanted the PATHs to reset on subshells I'd love to hear the usecase. I haven't been able to think of any yet. Thanks!

**Comment by MikeMcQuaid** [comment]
I think in general because often the profile is loaded once on e.g. graphical environment login and I want to be able to modify `~/.shrc` and have it load my new `PATH` on new shells without logout (or changing Terminal defaults to make them all login shells).

**Comment by AlJohri** [comment]
ah okay, that makes a lot of sense. I wish there was a more general way to solve that! I mostly spend time in macOS and only ssh into linux boxes so setting the PATH in login sessions works for me
